
package br.com.fiap.fornecedor.client.financeira;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Cobrar_ClienteService", targetNamespace = "http://finCliente.com.br/", wsdlLocation = "http://54.205.89.34/FinanciamentoMBA/Cobrar_Cliente?wsdl")
public class CobrarClienteService
    extends Service
{

    private final static URL COBRARCLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException COBRARCLIENTESERVICE_EXCEPTION;
    private final static QName COBRARCLIENTESERVICE_QNAME = new QName("http://finCliente.com.br/", "Cobrar_ClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://54.205.89.34/FinanciamentoMBA/Cobrar_Cliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COBRARCLIENTESERVICE_WSDL_LOCATION = url;
        COBRARCLIENTESERVICE_EXCEPTION = e;
    }

    public CobrarClienteService() {
        super(__getWsdlLocation(), COBRARCLIENTESERVICE_QNAME);
    }

    public CobrarClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COBRARCLIENTESERVICE_QNAME, features);
    }

    public CobrarClienteService(URL wsdlLocation) {
        super(wsdlLocation, COBRARCLIENTESERVICE_QNAME);
    }

    public CobrarClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COBRARCLIENTESERVICE_QNAME, features);
    }

    public CobrarClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CobrarClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CobrarCliente
     */
    @WebEndpoint(name = "Cobrar_ClientePort")
    public CobrarCliente getCobrarClientePort() {
        return super.getPort(new QName("http://finCliente.com.br/", "Cobrar_ClientePort"), CobrarCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CobrarCliente
     */
    @WebEndpoint(name = "Cobrar_ClientePort")
    public CobrarCliente getCobrarClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://finCliente.com.br/", "Cobrar_ClientePort"), CobrarCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COBRARCLIENTESERVICE_EXCEPTION!= null) {
            throw COBRARCLIENTESERVICE_EXCEPTION;
        }
        return COBRARCLIENTESERVICE_WSDL_LOCATION;
    }

}
