
package br.com.fiap.fornecedor.client.financeira;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cobrar_Cliente", targetNamespace = "http://finCliente.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CobrarCliente {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cobrar", targetNamespace = "http://finCliente.com.br/", className = "br.com.fiap.fornecedor.client.financeira.Cobrar")
    @ResponseWrapper(localName = "cobrarResponse", targetNamespace = "http://finCliente.com.br/", className = "br.com.fiap.fornecedor.client.financeira.CobrarResponse")
    public boolean cobrar(
        @WebParam(name = "arg0", targetNamespace = "")
        Cobranca arg0);

}
