
package br.com.fiap.fornecedor.client.governo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GovernoService", targetNamespace = "http://ws.governo.com.br/", wsdlLocation = "http://52.15.126.233/fiap-governo-ws/Governo?wsdl")
public class GovernoService
    extends Service
{

    private final static URL GOVERNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException GOVERNOSERVICE_EXCEPTION;
    private final static QName GOVERNOSERVICE_QNAME = new QName("http://ws.governo.com.br/", "GovernoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://52.15.126.233/fiap-governo-ws/Governo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GOVERNOSERVICE_WSDL_LOCATION = url;
        GOVERNOSERVICE_EXCEPTION = e;
    }

    public GovernoService() {
        super(__getWsdlLocation(), GOVERNOSERVICE_QNAME);
    }

    public GovernoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GOVERNOSERVICE_QNAME, features);
    }

    public GovernoService(URL wsdlLocation) {
        super(wsdlLocation, GOVERNOSERVICE_QNAME);
    }

    public GovernoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GOVERNOSERVICE_QNAME, features);
    }

    public GovernoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GovernoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Governo
     */
    @WebEndpoint(name = "GovernoPort")
    public Governo getGovernoPort() {
        return super.getPort(new QName("http://ws.governo.com.br/", "GovernoPort"), Governo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Governo
     */
    @WebEndpoint(name = "GovernoPort")
    public Governo getGovernoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.governo.com.br/", "GovernoPort"), Governo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GOVERNOSERVICE_EXCEPTION!= null) {
            throw GOVERNOSERVICE_EXCEPTION;
        }
        return GOVERNOSERVICE_WSDL_LOCATION;
    }

}
